export const HTTP_EXCEPTION_ERROR_MESSAGES = {
  AGENT_UNAUTHORIZED_ACTION: 'This agent cannot perform this action',
  FORBIDDEN_RESOURCE: 'forbidden resource',
  INVALID_JWT_TOKEN: 'invalid token',
  MISSING_JWT_TOKEN: 'missing JWT token',
  MISSING_DATA_PAYLOAD: 'missing user data in payload',
  USER_DOES_NOT_EXIST: "user doesn't exist",
  COMPANY_DOES_NOT_EXIST: "company doesn't exist",
  USER_EMAIL_MUST_UNIQUE: "user's email must be unique",
  GROUP_DOES_NOT_EXIST: "group doesn't exist",
  GROUP_HAS_MEMBERS: 'group has members that cannot be removed',
  GROUP_DISP_NAME_MUST_UNIQUE: "group's display name must be unique",
  PHONE_NUMBER_DOES_NOT_EXIST: "phone number doesn't exist",
  PHONE_NUMBER_MUST_UNIQUE: 'phone number must be unique',
  PHONE_NUMBER_DOMAIN_AND_ACCOUNT_MUST_UNIQUE:
    'domain and account id must be unique',
  CUSTOMER_DOES_NOT_EXIST: "customer doesn't exist",
  IVR_FLOW_DOES_NOT_EXIST: "ivr flow doesn't exist",
  IVR_AUDIO_DOES_NOT_EXIST: "ivr audio doesn't exist",
  ROLE_DOES_NOT_EXIST: "role doesn't exist",
  ROLE_MUST_UNIQUE: 'role name must be unique',
  PHONE_NUMBER_EXIST: 'phone number exists',
  AUDIO_EXIST: 'audio name exists',
  IVR_EXIST: 'ivr name exists',
  AGENT_USER_IS_BEING_USED: 'cannot delete while agent user is being used',
  ROLE_IS_BEING_ASSIGNED: 'cannot delete role while being assigned to user',
  ROLE_DEFAULT_CANNOT_BE_DELETED: 'cannot delete role default',
  ENTRY_POINT_ERROR: 'Entry point must point to 1 node',
  CUSTOMER_INPUT_INVALID_DATA:
    'Customer Input node must have audio file and branches',
  CUSTOMER_INPUT_INVALID_CONNECTION:
    'Missing connections of Customer Input node',
  WORKING_HOUR_INVALID_DATA: 'Working Hour node must have branches',
  WORKING_HOUR_INVALID_CONNECTION: 'Missing connections of Working Hour node',
  VOICE_INVALID_DATA: 'Voice node must have audio file',
  VOICE_INVALID_CONNECTION: 'Missing connections of Voice node',
  CONTACT_TARGET_INVALID_DATA:
    'Contact target node must transfer to a group or agent',
  CONTACT_TARGET_INVALID_GROUP: 'Contact target node must transfer to a group',
  CONTACT_TARGET_INVALID_AGENT: 'Contact target node must transfer to a agent',
  CONTACT_TARGET_INVALID_CONNECTION:
    'Missing connections of Contact target node',
  NODE_INVALID_CONNECTION: 'Missing connections of nodes',
  CALL_LOG_DOES_NOT_EXIST: "call log doesn't exist",
  CALL_LOG_QUERY_MISSING_PHONE_NUMBER:
    'You must provide a phone number when selecting type',
  CUSTOMER_NOTE_DOES_NOT_EXIST: 'This note does not exist',
  TRANSCRIPT_LINK_DOES_NOT_EXIST: 'Transcript link doesnt exist',
  NOTE_DOES_NOT_EXIST: 'This note does not exist',
  COMPANY_CODE_INVALID: 'Company code is invalid',
  CALL_NOTE_DOES_NOT_EXIST: 'call note doesnt exist',
  CALL_NOTE_CREATE_MORE_THAN_ONE: 'cannot create more note for this call log',
  CALL_NOTE_MEMO_TAG_MUST_UNIQUE: 'call note memo must be unique',
  CALL_NOTE_MEMO_TAG_DOES_NOT_EXIST: 'call note memo tag doesnt exist',
  CUSTOMER_PHONE_NUMBER_EXIST:
    'customer with this phone number already existed',
  CUSTOMER_EMAIL_EXIST: 'customer with this email already existed',
  CUSTOMER_COMPANY_DOES_NOT_EXIST: 'customer company doesnt exist',
  CUSTOMER_COMPANY_ALREADY_EXISTED: 'customer company already existed',
  CUSTOMER_COMPANY_CREATE_FAILED: 'failed to create customer company',
  CUSTOMER_COMPANY_FIND_FAILED: 'failed to find customer company',
  DEVICE_DOES_NOT_EXIST: 'Device doesnt exist',
  ROOT_USER_CANNOT_BE_DELETED: 'cannot delete root user',
  ROOT_USER_CANNOT_REMOVE_ROLE_DEFAULT:
    'cannot remove default role of root user',
  SLACK_WORKSPACE_DOES_NOT_EXIST: 'slack workspace doesnt exist',
  SLACK_AUTHED_USER_DOES_NOT_EXIST:
    'authed user on slack workspace doesnt exist',
};

export const HTTP_RESPONSE_MESSAGE = {
  SUCCESSFULLY_DELETE_NOTE: (id: number) =>
    `Successfully remove the note ${id}`,
};

export const HTTP_EXCEPTION_ERROR_CODE = {
  // INTERNAL ERROR: 10XX
  FORBIDDEN_RESOURCE: 1000,
  VALIDATION_ERROR: 1001,
  JWT_VALIDATION_ERROR: 1002,
  MISSING_JWT_TOKEN: 1003,
  // GOTRUE AUTH: 11XX
  GOTRUE_FORBIDDEN: 1101,
  GOTRUE_AUTH_FAILED: 1102,
  GOTRUE_FAILED: 1103,

  // USER: 20XX
  USER_DOES_NOT_EXIST: 2001,
  USER_UPDATE_FORBIDDEN: 2002,
  USER_UPDATE_FAILED: 2003,
  USER_FIND_FAILED: 2004,
  UNAUTHORIZED_TO_REMOVE_USER: 2005,
  USER_DELETE_FAILED: 2006,
  USER_LIST_FAILED: 2007,
  USER_CREATE_FAILED: 2008,
  USER_EMAIL_MUST_UNIQUE: 2009,
  ROOT_USER_CANNOT_BE_DELETED: 2010,
  ROOT_USER_CANNOT_REMOVE_ROLE_DEFAULT: 2011,
  // COMPANY: 21XX
  COMPANY_DOES_NOT_EXIST: 2100,
  COMPANY_CREATE_FAILED: 2101,
  UNAUTHORIZED_COMPANY_ACCESS: 2103,
  COMPANY_CODE_INVALID: 2104,
  // CUSTOMER: 22XX
  CUSTOMER_DOES_NOT_EXIST: 2200,
  CUSTOMER_CREATE_FAILED: 2201,
  CUSTOMER_FIND_ALL_FAILED: 2202,
  CUSTOMER_FIND_FAILED: 2203,
  CUSTOMER_UPDATE_FAILED: 2204,
  CUSTOMER_DELETE_FAILED: 2205,
  CUSTOMER_EMAIL_EXIST: 2206,
  CUSTOMER_PHONE_NUMBER_EXIST: 2207,
  CUSTOMER_COMPANY_DOES_NOT_EXIST: 2208,
  CUSTOMER_COMPANY_ALREADY_EXISTED: 2209,
  CUSTOMER_COMPANY_CREATE_FAILED: 2210,
  CUSTOMER_COMPANY_FIND_FAILED: 2211,
  // AGENT: 24XX
  AGENT_LOGIN_FAILED: 2400,
  AGENT_LOGOUT_FAILED: 2401,
  AGENT_USER_IS_BEING_USED: 2402,
  AGENT_STATUS_FIND_FAILED: 2403,
  AGENT_STATUS_UPDATE_FAILED: 2404,
  AGENT_NOT_FOUND: 2405,
  AGENT_UNAUTHORIZED_ACTION: 2406,
  // ROLE: 25XX
  ROLE_IS_BEING_ASSIGNED: 2500,
  ROLE_DOES_NOT_EXIST: 2501,
  ROLE_CREATE_FAILED: 2502,
  ROLE_FIND_ALL_FAILED: 2503,
  ROLE_UPDATE_FAILED: 2504,
  ROLE_REMOVE_FAILED: 2505,
  ROLE_MUST_UNIQUE: 2506,
  ROLE_DEFAULT_CANNOT_BE_DELETED: 2507,
  // GROUP: 26XX
  GROUP_DOES_NOT_EXIST: 2601,
  GROUP_HAS_MEMBERS: 2602,
  GROUP_DISP_NAME_MUST_UNIQUE: 2603,
  GROUP_FIND_FAILED: 2604,
  GROUP_CREATE_FAILED: 2605,
  GROUP_UPDATE_FAILED: 2606,
  GROUP_DELETE_FAILED: 2607,
  GROUP_FIND_ALL_FAILED: 2608,
  GROUP_MEMBER_ADD_FAILED: 2609,
  GROUP_MEMBER_REMOVE_FAILED: 2610,
  GROUP_EXISTING_MEMBER_ADD_FAILED: 2611,

  // PHONE NUMBER: 30XX
  PHONE_NUMBER_DOES_NOT_EXIST: 3001,
  PHONE_NUMBER_MUST_UNIQUE: 3002,
  PHONE_NUMBER_EXIST: 3003,
  PHONE_NUMBER_CANNOT_BE_CREATED: 3004,
  PHONE_NUMBER_LIST_FAILED: 3005,
  PHONE_NUMBER_FIND_FAILED: 3006,
  PHONE_NUMBER_UPDATE_FAILED: 3007,
  PHONE_NUMBER_DELETE_FAILED: 3008,
  PHONE_NUMBER_DOMAIN_AND_ACCOUNT_MUST_UNIQUE: 3009,
  // IVR: 31XX
  IVR_FLOW_DOES_NOT_EXIST: 3101,
  IVR_AUDIO_DOES_NOT_EXIST: 3102,
  IVR_EXIST: 3103,
  IVR_CREATE_FAILED: 3104,
  IVR_FIND_FAILED: 3105,
  IVR_UPDATE_FAILED: 3106,
  IVR_DELETE_FAILED: 3107,
  // IVR CUSTOMER INPUT: 32XX
  CUSTOMER_INPUT_INVALID_DATA: 3201,
  CUSTOMER_INPUT_INVALID_CONNECTION: 3202,
  // IVR VOICE: 33XX
  VOICE_INVALID_DATA: 3301,
  VOICE_INVALID_CONNECTION: 3303,
  // IVR CONTACT TARGET: 34XX
  CONTACT_TARGET_INVALID_DATA: 3401,
  CONTACT_TARGET_INVALID_GROUP: 3402,
  CONTACT_TARGET_INVALID_AGENT: 3403,
  CONTACT_TARGET_INVALID_CONNECTION: 3404,
  // IVR NODE: 35XX
  ENTRY_POINT_ERROR: 3500,
  NODE_INVALID_CONNECTION: 3501,
  // IVR AUDIO
  AUDIO_EXIST: 3601,
  IVR_AUDIO_CREATE_FAILED: 3602,
  IVR_AUDIO_FIND_ALL_FAILED: 3603,
  // IVR WORKING HOUR: 37XX
  WORKING_HOUR_INVALID_DATA: 3701,
  WORKING_HOUR_INVALID_CONNECTION: 3702,
  // CALL LOG: 40XX
  CALL_LOG_DOES_NOT_EXIST: 4001,
  CALL_LOG_QUERY_MISSING_PHONE_NUMBER: 4002,
  CALL_LOGS_LIST_FAILED: 4003,
  CALL_LOG_FIND_FAILED: 4004,
  CALL_LOG_AGGREGATION_CANNOT_BE_RETRIEVED: 4005,
  // CUSTOMER NOTE: 41XX
  CUSTOMER_NOTE_DOES_NOT_EXIST: 4100,
  CUSTOMER_NOTE_CREATE_FAILED: 4101,
  CUSTOMER_NOTE_FIND_FAILED: 4102,
  CUSTOMER_NOTE_UPDATE_FAILED: 4103,
  CUSTOMER_NOTE_DELETE_FAILED: 4104,
  // CALL NOTE: 42XX
  CALL_NOTE_DOES_NOT_EXIST: 4201,
  CALL_NOTE_CREATE_FAILED: 4202,
  CALL_NOTE_UPDATE_FAILED: 4203,
  CALL_NOTE_DELETE_FAILED: 4204,
  CALL_NOTE_CREATE_MORE_THAN_ONE: 4205,
  // DEVICE TOKEN: 43xx
  DEVICE_TOKEN_DOES_NOT_EXIST: 4301,
  // CALL NOTE TAG: 44xx
  CALL_NOTE_MEMO_TAG_FIND_FAILED: 4401,
  CALL_NOTE_MEMO_TAG_CREATE_UPDATE_FAILED: 4402,
  CALL_NOTE_MEMO_TAG_DELETE_FAILED: 4403,
  CALL_NOTE_MEMO_TAG_MUST_UNIQUE: 4404,
  CALL_NOTE_MEMO_TAG_DOES_NOT_EXIST: 4405,
  TRANSCRIPT_LINK_DOES_NOT_EXIST: 6001,
  // LINKING WORKSPACE: 5XXX
  // SLACK: 51XX
  SLACK_WORKSPACE_AUTHENTICATION_FAILED: 5100,
  SLACK_WORKSPACE_DOES_NOT_EXIST: 5101,
  SLACK_AUTHED_USER_DOES_NOT_EXIST: 5102,
  SLACK_API_CALL_ERROR: 5103,
  SLACK_API_CHANNEL_NOT_FOUND: 5104,
  SLACK_API_USER_NOT_FOUND: 5105,
  SLACK_API_NOT_IN_CHANNEL: 5105,
  SLACK_API_ALREADY_IN_CHANNEL: 5106,
  SLACK_API_NOT_AUTHED: 5107,
  SLACK_API_INVALID_AUTH: 5108,
  SLACK_API_TOKEN_EXPIRED: 5109,
  SLACK_API_MISSING_SCOPE: 5110,
  SLACK_API_RATE_LIMITED: 5111,
  SLACK_API_REQUEST_TIMEOUT: 5112,
  SLACK_API_INTERNAL_ERROR: 5113,
  SLACK_API_CANT_INVITE: 5114,
  SLACK_API_INVALID_GRANT_TYPE: 5115,
  SLACK_API_INVALID_CLIENT_ID: 5116,
  SLACK_API_BAD_CLIENT_SECRET: 5117,
  SLACK_API_INVALID_CODE: 5118,
  SLACK_API_BAD_REDIRECT_URI: 5119,
};

export const HTTP_VALIDATION_ERROR_MESSAGE = {
  IsCustomerExisted: 'Customer does not exist',
};

export enum Strategy {
  ringall = 'ringall',
  roundrobin = 'roundrobin',
  leastrecent = 'leastrecent',
  fewestcalls = 'fewestcalls',
  random = 'random',
  rrmemory = 'rrmemory',
}

export enum GotrueRoles {
  ADMIN = 'admin',
  USER = 'user',
}

export enum nodeType {
  entryPoint = 'ENTRY_POINT',
  customerInput = 'CUSTOMER_INPUT',
  contactTarget = 'CONTACT_TARGET',
  voice = 'VOICE',
  disconnect = 'DISCONNECT',
  workingHour = 'WORKING_HOUR',
  voiceMail = 'VOICE_MAIL',
}

export enum CALL_LOG_DIRECTION {
  INCOMING = 'incoming',
  OUTGOING = 'outgoing',
}

export enum DEVICE_TYPE {
  WEB = 'WEB',
  IOS = 'IOS',
  ANDROID = 'ANDROID',
}

export enum AGGREGATION_CALL_TYPE {
  INCOMING = 'Incoming',
  OUTGOING = 'Outgoing',
  MISSED = 'Missed',
  ABSENT = 'Absent',
  ALL = 'All',
}

export enum AGGREGATION_PERIOD_CALL_LOG {
  THREE_DAYS = '3D',
  SEVEN_DAYS = '7D',
  FOURTEEN_DAYS = '14D',
  TWENTY_EIGHT_DAYS = '28D',
}

export enum USER_ROLE {
  DEFAULT = 'default',
}

export const MAPPING_SLACK_ERROR_TO_ERROR_CODE = {
  channel_not_found: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_CHANNEL_NOT_FOUND,
  user_not_found: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_USER_NOT_FOUND,
  not_in_channel: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_NOT_IN_CHANNEL,
  already_in_channel: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_ALREADY_IN_CHANNEL,
  not_authed: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_NOT_AUTHED,
  invalid_auth: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_INVALID_AUTH,
  token_expired: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_TOKEN_EXPIRED,
  missing_scope: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_MISSING_SCOPE,
  ratelimited: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_RATE_LIMITED,
  request_timeout: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_REQUEST_TIMEOUT,
  internal_error: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_INTERNAL_ERROR,
  cant_invite: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_CANT_INVITE,
  invalid_grant_type: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_INVALID_GRANT_TYPE,
  invalid_client_id: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_INVALID_CLIENT_ID,
  bad_client_secret: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_BAD_CLIENT_SECRET,
  invalid_code: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_INVALID_CODE,
  bad_redirect_uri: HTTP_EXCEPTION_ERROR_CODE.SLACK_API_BAD_REDIRECT_URI,
};
